    name: test
    
    on:
      push:
        branches:
          - main
        paths-ignore:
          - '**.md'
      pull_request:
        paths-ignore:
          - '**.md'
    
    env:
      BUILD_TAG: caddy-proxy-complete:test
      CONTAINER_NAME: caddy-proxy-complete

    jobs:
      test:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3

          # Add support for more platforms with QEMU (optional)
          - name: Set up QEMU
            uses: docker/setup-qemu-action@v3

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
      
          - name: Build
            uses: docker/bake-action@v4
            with:
              targets: image-local
            env:
              DEFAULT_TAG: ${{ env.BUILD_TAG }}
          
          - name: Start
            run: |
              docker compose up -d
            working-directory: test
            env:
              CADDY_DOCKER_PROXY_IMAGE: ${{ env.BUILD_TAG }}
              CADDY_DOCKER_PROXY_CONTAINER: ${{ env.CONTAINER_NAME }}

          - name: Check container logs
            uses: crazy-max/.github/.github/actions/container-logs-check@main
            with:
              container_name: ${{ env.CONTAINER_NAME }}
              log_check: "serving initial configuration"
              timeout: 60

          - name: Check Loaded Modules
            id: caddy_list_module_output
            working-directory: test
            run: |
              docker compose exec -w /etc/caddy caddy caddy list-modules || echo $?

