    name: docker-publish
    
    on:
      workflow_dispatch:
    
    env:
      BUILD_TAG: ${{ github.event.repository.name }}:latest
      CONTAINER_NAME: ${{ github.event.repository.name }}

    jobs:
      publish:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3

          # Add support for more platforms with QEMU (optional)
          - name: Set up QEMU
            uses: docker/setup-qemu-action@v3

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
      
          - name: Build
            uses: docker/bake-action@v4
            with:
              targets: image-local
            env:
              DEFAULT_TAG: ${{ env.BUILD_TAG }}
          
          - name: Login to GitHub Container Registry
            uses: docker/login-action@v2
            with:
              registry: ghcr.io
              username: ${{ github.repository_owner }}
              password: ${{ secrets.GITHUB_TOKEN }}
              logout: false
          
          - name: Build and push release image
            uses: docker/build-push-action@v3
            with:
              context: .
              file: ./Dockerfile
              push: true
              tags: "ghcr.io/${{ github.event.repository.owner.login }}/${{ github.event.repository.name }}:latest"
              platforms: linux/amd64,linux/arm64
              
