    name: test
    on:
      push:
        branches:
          - main
      pull_request:
    jobs:
      test:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3

          - name: Check Dockerfile Build 
            run: |
              docker build -t caddy-docker-proxy -f Dockerfile .
              if [ $? -ne 0 ]; then
                echo "Error building image"
                exit 1
              fi

          - name: Check container logs
            uses: crazy-max/.github/.github/actions/container-logs-check@main
            with:
              container_name: ${{ env.CONTAINER_NAME }}
              log_check: "serving initial configuration"
              timeout: 60

          - name: Check Loaded Modules
            id: caddy_list_module_output
            run: |
              docker run -it caddy-docker-proxy sh -c "caddy list-modules"

