    name: test
    
    on:
      push:
        branches:
          - main
      pull_request:
    
    env:
      Build_TAG: caddy-docker-proxy:test
      CONTAINER_NAME: caddy-docker-proxy

    jobs:
      test:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3

          # Add support for more platforms with QEMU (optional)
          - name: Set up QEMU
            uses: docker/setup-qemu-action@v3

          - name: Set up Docker Buildx
             uses: docker/setup-buildx-action@v3
      
          - name: Build
            uses: docker/bake-action@v4
            with:
              targets: image-local
            env:
              DEFAULT_TAG: ${{ env.BUILD_TAG }}
      
          - name: Start
             run: |
               docker compose up -d
             working-directory: test
             env:
               LIBRENMS_IMAGE: ${{ env.BUILD_TAG }}
               LIBRENMS_CONTAINER: ${{ env.CONTAINER_NAME }}

          - name: Check container logs
            uses: crazy-max/.github/.github/actions/container-logs-check@main
            with:
              container_name: ${{ env.CONTAINER_NAME }}
              log_check: "serving initial configuration"
              timeout: 60

          - name: Check Loaded Modules
            id: caddy_list_module_output
            run: |
              docker run -it caddy-docker-proxy sh -c "caddy list-modules"

