name: Update caddy-dns/porkbun

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 10 * * *'

permissions:
  pull-requests: write
  contents: write

jobs:
  updated-module-dns-porkbun:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get Latest caddy-dns/porkbun Release
        id: dns-porkbun
        run: |
          release_tag=$(curl -sL https://api.github.com/repos/caddy-dns/porkbun/releases/latest | jq -r ".tag_name")
          echo "release_tag=$release_tag" >> $GITHUB_OUTPUT
          current_tag=$(<dns-porkbun.version)
          echo "current_tag=$current_tag" >> $GITHUB_OUTPUT

      - name: Replace string in file
        if: steps.dns-porkbun.outputs.current_tag != steps.dns-porkbun.outputs.release_tag 
        uses: MathieuSoysal/replace-string-in-file@v1.0.0
        with:
          file: Dockerfile
          old-string: ${{ steps.dns-porkbun.outputs.current_tag }}
          new-string: ${{ steps.dns-porkbun.outputs.release_tag }}
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Updateto ${{ steps.dns-porkbun.outputs.release_tag }}
          title: Update dns.providers.porkbun to ${{ steps.dns-porkbun.outputs.release_tag }}
          body: |
            Updates [dns-porkbun][1] to ${{ steps.dns-porkbun.outputs.release_tag }}

            Auto-generated by [create-pull-request][2]

            [1]: https://github.com/caddy-dns/porkbun
            [2]: https://github.com/peter-evans/create-pull-request
          labels: dependencies, automated pr
